apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user-reader-binding
  namespace: user-ns
subjects:
- kind: User
  name: rnd-user
roleRef:
  kind: Role
  name: user-reader
  apiGroup: rbac.authorization.k8s.io
